import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import { BiFilterContext, calculateBiMetrics } from './biEngine';

export interface ReportExportMetadata {
  title: string;
  generatedBy: string;
  generatedAt: string;
  filters: BiFilterContext;
}

// Format currency
const formatMoney = (amount: number) => `₱${amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

// 1. EXCEL EXPORT (Multi-Sheet Workbook via SheetJS)
export function exportExecutiveReportToExcel(
  metrics: ReturnType<typeof calculateBiMetrics>,
  metadata: ReportExportMetadata
) {
  const wb = XLSX.utils.book_new();

  // --- SHEET 1: EXECUTIVE SUMMARY ---
  const summaryRows = [
    ['FFCSI AFMS EXECUTIVE MANAGEMENT BI REPORT'],
    ['Report Title', metadata.title],
    ['Generated By', metadata.generatedBy],
    ['Timestamp', metadata.generatedAt],
    ['Date Range', `${metadata.filters.startDate} to ${metadata.filters.endDate}`],
    ['Filters Applied', `Client: ${metadata.filters.clientId} | Staff: ${metadata.filters.staffId} | Service: ${metadata.filters.serviceCategory} | RDO: ${metadata.filters.rdoCode}`],
    [''],
    ['EXECUTIVE KEY PERFORMANCE INDICATORS', 'VALUE'],
    ['Total Clients', metrics.clientAnalytics.totalClients],
    ['Active Clients', metrics.clientAnalytics.activeCount],
    ['New Clients (Period)', metrics.clientAnalytics.newClientsCount],
    ['Total Billed Period Revenue', formatMoney(metrics.revenueAnalytics.periodRevenue)],
    ['Monthly Revenue (Current)', formatMoney(metrics.revenueAnalytics.monthlyRevenue)],
    ['Quarterly Revenue (Current)', formatMoney(metrics.revenueAnalytics.quarterlyRevenue)],
    ['Annual Revenue (Current)', formatMoney(metrics.revenueAnalytics.annualRevenue)],
    ['Monthly Recurring Revenue (MRR)', formatMoney(metrics.serviceProfitability.monthlyRecurringRevenue)],
    ['Total Outstanding AR', formatMoney(metrics.arAging.totalOutstanding)],
    ['AR Over 90 Days (Severely Overdue)', formatMoney(metrics.arAging.over90)],
    ['AR Collection Rate', `${metrics.arAging.collectionRatePercentage}%`],
    ['Compliance Completion Rate', `${metrics.compliancePerformance.completionRatePercentage}%`],
    ['Overdue Compliance Tasks', metrics.compliancePerformance.tasksOverdue]
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive Summary');

  // --- SHEET 2: REVENUE & SERVICE PROFITABILITY ---
  const revenueRows = [
    ['SERVICE NAME', 'CATEGORY', 'REVENUE', '% OF REVENUE', 'CLIENT COUNT', 'AVG FEE'],
    ...metrics.serviceProfitability.totalRevenueByService.map(s => [
      s.serviceName,
      s.category,
      formatMoney(s.totalRevenue),
      `${metrics.revenueAnalytics.periodRevenue > 0 ? Math.round((s.totalRevenue / metrics.revenueAnalytics.periodRevenue) * 100) : 0}%`,
      s.clientCount,
      formatMoney(s.averageFee)
    ])
  ];
  const wsRevenue = XLSX.utils.aoa_to_sheet(revenueRows);
  XLSX.utils.book_append_sheet(wb, wsRevenue, 'Service Revenue');

  // --- SHEET 3: ACCOUNTS RECEIVABLE & AGING ---
  const arRows = [
    ['CLIENT NAME', 'TOTAL OUTSTANDING', 'OVERDUE INVOICES', 'OLDEST DUE DATE', 'DAYS OVERDUE'],
    ...metrics.arAging.topOutstandingClients.map(c => [
      c.clientName,
      formatMoney(c.totalOutstanding),
      c.overdueInvoicesCount,
      c.oldestDueDate,
      c.daysOverdue
    ])
  ];
  const wsAr = XLSX.utils.aoa_to_sheet(arRows);
  XLSX.utils.book_append_sheet(wb, wsAr, 'AR Aging');

  // --- SHEET 4: STAFF PRODUCTIVITY & COMPLIANCE ---
  const staffRows = [
    ['STAFF NAME', 'ASSIGNED CLIENTS', 'ASSIGNED TASKS', 'COMPLETED', 'OVERDUE', 'FOR REVIEW', 'COMPLETION RATE', 'WORKLOAD'],
    ...metrics.staffProductivity.staffList.map(s => [
      s.staffName,
      s.assignedClientsCount,
      s.assignedTasksCount,
      s.completedTasksCount,
      s.overdueTasksCount,
      s.forReviewTasksCount,
      `${s.completionRate}%`,
      s.workloadLevel
    ])
  ];
  const wsStaff = XLSX.utils.aoa_to_sheet(staffRows);
  XLSX.utils.book_append_sheet(wb, wsStaff, 'Staff Productivity');

  // Trigger Download
  const safeFilename = `FFCSI_AFMS_BI_Report_${metadata.generatedAt.replace(/[: ]/g, '_')}.xlsx`;
  XLSX.writeFile(wb, safeFilename);
}

// 2. CSV EXPORT
export function exportExecutiveReportToCsv(
  metrics: ReturnType<typeof calculateBiMetrics>,
  metadata: ReportExportMetadata
) {
  const lines: string[] = [];

  lines.push(`"FFCSI AFMS EXECUTIVE MANAGEMENT REPORT"`);
  lines.push(`"Generated By:","${metadata.generatedBy}"`);
  lines.push(`"Timestamp:","${metadata.generatedAt}"`);
  lines.push(`"Date Range:","${metadata.filters.startDate} to ${metadata.filters.endDate}"`);
  lines.push(`"Filters:","Client: ${metadata.filters.clientId} | Staff: ${metadata.filters.staffId} | Category: ${metadata.filters.serviceCategory}"`);
  lines.push(``);

  lines.push(`"--- EXECUTIVE SUMMARY METRICS ---"`);
  lines.push(`"Metric","Value"`);
  lines.push(`"Total Clients",${metrics.clientAnalytics.totalClients}`);
  lines.push(`"Active Clients",${metrics.clientAnalytics.activeCount}`);
  lines.push(`"New Clients (Period)",${metrics.clientAnalytics.newClientsCount}`);
  lines.push(`"Period Billed Revenue",${metrics.revenueAnalytics.periodRevenue}`);
  lines.push(`"Monthly Recurring Revenue (MRR)",${metrics.serviceProfitability.monthlyRecurringRevenue}`);
  lines.push(`"Total Outstanding AR",${metrics.arAging.totalOutstanding}`);
  lines.push(`"AR Over 90 Days",${metrics.arAging.over90}`);
  lines.push(`"Collection Rate %",${metrics.arAging.collectionRatePercentage}`);
  lines.push(`"Compliance Completion Rate %",${metrics.compliancePerformance.completionRatePercentage}`);
  lines.push(``);

  lines.push(`"--- TOP OUTSTANDING ACCOUNTS RECEIVABLE ---"`);
  lines.push(`"Client Name","Total Outstanding","Overdue Invoices Count","Oldest Due Date","Days Overdue"`);
  metrics.arAging.topOutstandingClients.forEach(c => {
    lines.push(`"${c.clientName}",${c.totalOutstanding},${c.overdueInvoicesCount},"${c.oldestDueDate}",${c.daysOverdue}`);
  });
  lines.push(``);

  lines.push(`"--- STAFF PRODUCTIVITY ---"`);
  lines.push(`"Staff Name","Assigned Clients","Assigned Tasks","Completed","Overdue","Completion Rate %","Workload"`);
  metrics.staffProductivity.staffList.forEach(s => {
    lines.push(`"${s.staffName}",${s.assignedClientsCount},${s.assignedTasksCount},${s.completedTasksCount},${s.overdueTasksCount},${s.completionRate},"${s.workloadLevel}"`);
  });

  const csvContent = lines.join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `FFCSI_AFMS_BI_Report_${metadata.generatedAt.replace(/[: ]/g, '_')}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

// 3. PDF EXPORT (Formatted Multi-Page Document)
export function exportExecutiveReportToPdf(
  metrics: ReturnType<typeof calculateBiMetrics>,
  metadata: ReportExportMetadata
) {
  const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });

  let y = 15;

  // Header Box
  doc.setFillColor(30, 41, 59); // Slate-800
  doc.rect(10, 10, 190, 25, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('FFCSI AFMS — EXECUTIVE BI & MANAGEMENT REPORT', 15, 20);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated By: ${metadata.generatedBy}  |  Timestamp: ${metadata.generatedAt}`, 15, 28);
  doc.text(`Date Range: ${metadata.filters.startDate} to ${metadata.filters.endDate}`, 15, 32);

  y = 42;

  // Section 1: Executive KPI Summary
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Executive Key Performance Indicators', 12, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  const kpis = [
    ['Total Clients', `${metrics.clientAnalytics.totalClients} (${metrics.clientAnalytics.activeCount} Active)`],
    ['New Clients Onboarded', `${metrics.clientAnalytics.newClientsCount}`],
    ['Total Period Revenue', formatMoney(metrics.revenueAnalytics.periodRevenue)],
    ['Monthly Recurring Revenue (MRR)', formatMoney(metrics.serviceProfitability.monthlyRecurringRevenue)],
    ['Total Outstanding AR', formatMoney(metrics.arAging.totalOutstanding)],
    ['AR Over 90 Days', formatMoney(metrics.arAging.over90)],
    ['Collection Rate', `${metrics.arAging.collectionRatePercentage}%`],
    ['Compliance Completion Rate', `${metrics.compliancePerformance.completionRatePercentage}%`]
  ];

  doc.setDrawColor(226, 232, 240);
  kpis.forEach(([label, val]) => {
    doc.text(label, 15, y);
    doc.text(val, 130, y, { align: 'right' });
    doc.line(15, y + 1.5, 185, y + 1.5);
    y += 6;
  });

  y += 4;

  // Section 2: Top Accounts Receivable
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('2. Top Outstanding Accounts Receivable (AR)', 12, y);
  y += 6;

  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(12, y, 186, 6, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('Client Name', 15, y + 4);
  doc.text('Outstanding Amount', 110, y + 4, { align: 'right' });
  doc.text('Invoices', 145, y + 4, { align: 'right' });
  doc.text('Days Overdue', 185, y + 4, { align: 'right' });

  y += 8;
  doc.setFont('helvetica', 'normal');

  metrics.arAging.topOutstandingClients.slice(0, 8).forEach((c) => {
    doc.text(c.clientName.substring(0, 45), 15, y);
    doc.text(formatMoney(c.totalOutstanding), 110, y, { align: 'right' });
    doc.text(`${c.overdueInvoicesCount}`, 145, y, { align: 'right' });
    doc.text(`${c.daysOverdue} days`, 185, y, { align: 'right' });
    y += 5;
  });

  y += 6;

  // Section 3: Staff Productivity & Workload
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('3. Staff Capacity & Compliance Performance', 12, y);
  y += 6;

  doc.setFillColor(241, 245, 249);
  doc.rect(12, y, 186, 6, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('Staff Officer', 15, y + 4);
  doc.text('Clients', 85, y + 4, { align: 'right' });
  doc.text('Assigned Tasks', 120, y + 4, { align: 'right' });
  doc.text('Completion Rate', 155, y + 4, { align: 'right' });
  doc.text('Workload', 185, y + 4, { align: 'right' });

  y += 8;
  doc.setFont('helvetica', 'normal');

  metrics.staffProductivity.staffList.slice(0, 8).forEach((s) => {
    doc.text(s.staffName.substring(0, 30), 15, y);
    doc.text(`${s.assignedClientsCount}`, 85, y, { align: 'right' });
    doc.text(`${s.assignedTasksCount}`, 120, y, { align: 'right' });
    doc.text(`${s.completionRate}%`, 155, y, { align: 'right' });
    doc.text(s.workloadLevel, 185, y, { align: 'right' });
    y += 5;
  });

  // Footer on bottom of page
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('FFCSI Management Portal — Strictly Confidential Executive Document', 105, 285, { align: 'center' });

  // Save PDF
  const safeFilename = `FFCSI_AFMS_BI_Report_${metadata.generatedAt.replace(/[: ]/g, '_')}.pdf`;
  doc.save(safeFilename);
}
